# Generated by Django 4.0 on 2021-12-26 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeckPosition',
        ),
    ]
