# Generated by Django 4.0 on 2021-12-26 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_delete_deckposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='deck',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='learning.deck'),
            preserve_default=False,
        ),
    ]
