# Generated by Django 4.0 on 2021-12-26 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_queue_deck'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Queue',
        ),
    ]
