# Generated by Django 4.0 on 2021-12-26 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_queue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='deck',
        ),
    ]
