# Generated by Django 4.0 on 2021-12-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_queue_deck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=288, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
