# Generated by Django 4.0 on 2021-12-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_alter_profile_bio_alter_profile_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default=None, max_length=288),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
