# Generated by Django 4.0 on 2021-12-27 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_alter_profile_bio_alter_profile_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default=None, max_length=288),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fav_subject',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.subject'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
    ]
