# Generated by Django 4.0 on 2021-12-27 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('learning', '0015_profile_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_a', to='auth.user')),
                ('user_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_b', to='auth.user')),
            ],
        ),
    ]
