# Generated by Django 4.0 on 2021-12-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0017_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('REQUEST', 'REQUEST'), ('MESSAGE', 'MESSAGE')], default=1, max_length=7),
            preserve_default=False,
        ),
    ]
