# Generated by Django 4.0 on 2021-12-27 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0018_message_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='send_datum',
            new_name='send_date',
        ),
    ]
