# Generated by Django 4.0 on 2021-12-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0019_rename_send_datum_message_send_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('FRIEND-REQUEST', 'FRIEND-REQUEST'), ('MESSAGE', 'MESSAGE')], max_length=14),
        ),
    ]
