# Generated by Django 4.0 on 2021-12-27 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0020_alter_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='send_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
